plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/AspectOutputJars.java
plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/AspectOutputJarsTest.java

there was just a mismatch between the JSON parser and the Aspect file format. Parser was expecting 'srcjar', Aspect was writing 'source_jar'.

sourcejars now work, fixes #17

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/BazelNature.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerInitializer.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectSupport.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelProjectConstants.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationTab.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/api/JavaCoreHelper.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/api/ResourceHelper.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/impl/EclipseJavaCoreHelper.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/impl/EclipseResourceHelper.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/old/BazelWizard.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerFTest.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockIJavaProject.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockJavaCoreHelper.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockResourceHelper.java

In the interest of sending smaller PRs, these are just some initial changes I have made as I work on #5

Some general refactor related to issue #5 (projectview)

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/BazelPluginActivator.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferencePage.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockIJavaProject.java
plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelProcessBuilder.java

Simple fix for not being able to change bazel command in preferences

Fix for issue #76: Can change bazel runtime as long as file exists

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizardLocationControl.java

Sometimes when I try to import a bazel workspace, I make a silly mistake, like selecting "~".  I then have to kill Eclipse because we traverse all files below the selected dir.  This is an attempt at fixing that, by making users select the WORKSPACE file instead.

Select WORKSPACE file instead of a directory

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelAspectLocationImpl.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectSupport.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelProjectConfigurator.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelProjectHelper.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/importer/BazelProjectImportScanner.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/importer/BazelProjectImportScannerTest.java
plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java
plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelWorkspace.java

I saw IJ plugin just switched to canonical files, which seems like a good idea given all the soft links present in Bazel workspaces. This PR does the same for BEF.
https://github.com/bazelbuild/intellij/pull/1748/files

resolve Files to their canonicals

---

plugin-core/plugin.xml
plugin-core/src/main/java/com/salesforce/bazel/eclipse/BazelPluginActivator.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelProjectConfigurator.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/util/SelectionUtil.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizardLocationControl.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/command/BazelCommandRunnerFTest.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java
plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelQueryHelper.java
plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelPackageInfo.java
plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/BazelPackageInfoTest.java
plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelWorkspaceFactory.java

implement support for WORKSPACE.bazel and BUILD.bazel naming

---

docs/using_the_feature_import.md
plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/JavaLanguageLevelHelper.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/classpath/JavaLanguageLevelHelperTest.java

Infer JDK for build path from .bazelrc

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegate.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizardPage.java
plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelLauncherBuilder.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelLauncherBuilderTest.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommandBuilder.java
plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelLabel.java
plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelOutputDirectoryBuilder.java
plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/BazelLabelTest.java
plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/BazelOutputDirectoryBuilderTest.java

https://github.com/salesforce/bazel-eclipse/issues/94

Instead of "bazel run", directly call generated script

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java

Related to https://github.com/salesforce/bazel-eclipse/issues/96.  We will have to revisit this.

Call build explicitly for all imported downstream projects

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactoryFTest.java
plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelWorkspaceFactory.java
plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestJavaRuleCreator.java

import src/main/resources src/test/resources as source folders

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/BazelPluginActivator.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerInitializer.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelRuntimeClasspathProvider.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizardLocationControl.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelProjectImporter.java
plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelCommandManager.java

Improves behavior at startup if the preferences file is missing, and solves the Invalid Thread popups if there is an error during startup/import.

error handling

---

plugin-core/src/test/java/com/salesforce/bazel/eclipse/importer/BazelProjectImportScannerTest.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockEclipse.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockIJavaProject.java
plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelQueryHelper.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelLauncherBuilderTest.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunnerTest.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/internal/BazelCommandExecutorTest.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelperTest.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommandBuilder.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/TestBazelCommandEnvironmentFactory.java
plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelWorkspaceDescriptor.java
plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelWorkspaceFactory.java

this is just ground work for long term solution for making the tests more maintainable

adding in a descriptor for test workspaces

---

plugin-core/src/test/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerFTest.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelperTest.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommandBuilder.java

this fixes the tests, but not the test framework which needs work still

fix tests broken by test cp pr

---

plugin-core/plugin.xml
plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelJunitTargetLaunchShortcut.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationSupport.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationTab.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelTargetLaunchShortcut.java
plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/AspectPackageInfos.java

Also show bazel icon for launch configs and minor launch config tweaks

Enable console view red button (issue #71)

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java

mitigation for known issue #113  that can occur when user does a command line clean

limit the times diagnostics will be reported for #113

---

tools/eclipse_jars/eclipse_jars.bzl

Update Eclipse SDK version tracked in eclipse_jars.bzl to 4.13

Update Eclipse SDK version required

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/ImportOrderResolver.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/ImportOrderResolverImpl.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelProjectImporter.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/config/ImportOrderResolverTest.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockImportOrderResolver.java

fix tests from import ordering change

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java
plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/shell/ShellCommand.java
plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelDependencyGraph.java
plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/SimplePerfRecorder.java

points to Aspect computation as being the main perf issue for import

add perf instrumentation to import

---

plugin-core/src/test/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegateFTest.java
plugin-libs/plugin-command/BUILD
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelLauncherBuilderTest.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommand.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommandBuilder.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommandSimulatedOutput.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommandSimulatedOutputMatcher.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockBuildCommand.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockCleanCommand.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockInfoCommand.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockQueryCommand.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockTestCommand.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockVersionCommand.java

start of refactor to make writing tests that issue bazel commands much easier

refactor test commands

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java

This is a weird one. The ContainerViewer is throwing an unknown RuntimeException. This exception only happens on a fresh workspace and the first time the build file is changes and a project is added.
The proper fix might be to use asyncExec, but need a UI component to use it. This code is too low level and doesn't feel right to do that. I simply wrapped and logged the exception. This allows the container to recover (otherwise, it stays in a super bad state that requires an eclipse restart).
Open to discussion on this.
The exception is:
java.lang.RuntimeException
at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:764)
at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:531)
at org.eclipse.ui.navigator.CommonViewer.refresh(CommonViewer.java:352)
at …

Issue #39: Failure first time update build

---

plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockEclipse.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunnerTest.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/TestBazelCommandEnvironmentFactory.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockTestCommand.java
plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockVersionCommand.java
plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/BazelWorkspaceCommandOptionsTest.java
plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelWorkspaceDescriptor.java
plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelWorkspaceFactory.java
plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestOptions.java

some more test framework refinements, and starting to resolve test TODOs

more test work

---

plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/EclipseBazelProjectManager.java

I have been investigating how to reduce the number of triggered builds, and in some cases (e.g. if you refresh a project) it seems like being more careful about updating the project refs will reduce the number of unnecessary build commands.

only update project refs as necessary

---

bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/BazelProjectManager.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/BazelPluginActivator.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/JDTWarningPublisher.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/ResourceDeltaInspector.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerInitializer.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/builder/BazelBuilderTest.java

Some room for improvement, but this works pretty well for me.  Would like to get this merged and then have somebody else try a bit @plaird

Update classpath container for BUILD file changes #39

---

docs/using_the_feature_classpath.md
docs/using_the_feature_import.md
docs/using_the_feature_launching.md
docs/using_the_feature_preferences.md
plugin-core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferenceInitializer.java

- long overdue docs about classpaths in BEF
- explain new global preferences feature I added

docs for classpath and prefs

---

bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmClasspath.java

Fixes #170 
The fact that this fix didn't require updating any tests is a problem. There seems to be issues in the test framework.

fixes issue where libs from within package appeared in classpath

---

docs/using_the_feature_launching.md
docs/using_the_feature_preferences.md
docs/using_the_feature_settings.md
plugin-core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferenceInitializer.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferenceKeys.java

implements a more convenient way of adding new prefs and feature flags

improved preferences

---

bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelLabel.java
bzl-java-sdk/src/test/java/com/salesforce/bazel/sdk/model/BazelLabelTest.java
plugin-core/resources/bzleclipse_aspect.bzl
plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/ProjectImporterFactory.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/ImportFlow.java

- Generate a json file for every target visited, so that each "dep" listed
in the file has a corresponding aspect target info instance
- Make BazelLabel repository aware

Fix project import #131

---

bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelDependencyGraph.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/FlowProjectImporter.java

At least the import proceeds, but the project references are wrong.

Workaround for #197 - break out of infinite recursion

---

bzl-java-sdk/BUILD
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelQueryHelper.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelLabel.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelPackageInfo.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/ProjectView.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/util/BazelConstants.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/util/BazelDirectoryStructureUtil.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/workspace/BazelPackageFinder.java
bzl-java-sdk/src/test/java/com/salesforce/bazel/sdk/model/BazelLabelTest.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/ResourceDeltaInspector.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelProjectConfigurator.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateProjectsFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/InitImportFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/BazelPackageContentAssistProcessor.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/ProjectViewEditor.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/ProjectViewProcessor.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/util/SelectionUtil.java

I will fix missing header comments (Copyright) in my next PR.

Support parent dirs in projectview, centralize build file names #69

---

bzl-java-sdk/src/main/java/com/salesforce/bazel/app/analyzy/BazelAnalyzyApp.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelWorkspaceCommandRunner.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelQueryHelper.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelWorkspaceAspectHelper.java
bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmClasspath.java
bzl-java-sdk/src/test/java/com/salesforce/bazel/sdk/command/BazelWorkspaceCommandRunnerTest.java
bzl-java-sdk/src/test/java/com/salesforce/bazel/sdk/command/internal/BazelWorkspaceAspectHelperTest.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationSupport.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/ProjectImporter.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateProjectsFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateRootProjectFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/DetermineTargetsFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/FlowProjectImporter.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/ImportContext.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/ImportFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/InitImportFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/InitJREFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/LoadAspectsFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/LoadTargetsFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/OrderProjectsFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/SetupClasspathContainersFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/SetupProjectBuildersFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/SetupRootClasspathContainerFlow.java
plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelProjectImporter.java
plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java

This fixes the progress bar during import.

Saner progress reporting during project import

---

bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmClasspath.java

Fix for #211. Still need to add a test for it so will leave the issue open.

recognize java_import jars in classpath

---

bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/config/BazelAspectLocationImpl.java

To prevent breakages from packaging changes/Eclipse version upgrades in the future.

add more validation for aspect loading

---

bundles/com.salesforce.bazel-java-sdk/META-INF/MANIFEST.MF
bundles/com.salesforce.bazel.eclipse.core/META-INF/MANIFEST.MF
bundles/com.salesforce.bazel.eclipse.deps/META-INF/MANIFEST.MF
features/com.salesforce.bazel.eclipse.feature/feature.xml
pom.xml
releng/mavenparent/pom.xml

Testing the tycho/git workflows for releasing BEF.

prep for 1.3.1 test release

---

bundles/com.salesforce.bazel-java-sdk.testframework/META-INF/MANIFEST.MF
bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/command/test/MockCommandSimulatedOutput.java
bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/command/test/TestBazelCommandEnvironmentFactory.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelLabel.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelPackageInfo.java
bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/EclipseProjectStructureInspector.java
bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/LoadAspectsFlow.java
tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/workspace/BazelWorkspaceScannerTest.java

Windows support is getting close....

fixes for Windows

---

docs/dev/dev_guide.md

I have been lax about running the formatter. Just tell everyone (and me) to configure it as a Save action.

formatter save action doc

---

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/workspace/BazelPackageFinder.java

Use Java streams to find all eligible BUILD files in a workspace in parallel, to speed up import of large workspaces.
@guw thanks for this! I found it in bazel-eclipse-ls.

parallel BUILD file detection for import

---

releng/mavenparent/pom.xml

@guw thanks for suggesting the fix, this does fix the target platform on Windows. Issue #250

fix Windows target platform

---

.github/create-update-site-rc.sh
.github/create-update-site.sh
.github/workflows/build-test-rc-deploy.yml
docs/dev/release.md

Workflow for producing release candidates prior to official releases.

create an RC release process

---

bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/FlowProjectImporter.java

While doing release testing, I hit an issue twice that resulted from forgetting to configure the Bazel executable before importing. It resulted in BEF getting into a bad state. Easier just to kill the import at the beginning if the executable is not correct.

halt import early if the bazel exec is not configured

---

bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferenceKeys.java
bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferencePage.java
docs/using_the_feature_classpath.md

enable global search by default in prefs

---

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmTestClasspathHelper.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelWorkspace.java

windows linefeed fix for junit launcher

---

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelWorkspaceCommandRunner.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelQueryHelper.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelBuildFile.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelWorkspace.java
bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/EclipseProjectStructureInspector.java

First chunk of the work for #8 which is to tolerate non-Maven file layouts (src/main/java, src/test/java).

initial implementation of non-Maven layout support

---

bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestAspectFileCreator.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmClasspath.java
tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerFTest.java

Bugs in TestAspectFileCreator in the test framework were the problem.

fix implicit cp test

---

bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectCreator.java
docs/bef/issues.md

Doc note for grpc classpath issue #325, and updated a log message during import.

doc note about grpc classpath

---

bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestBazelWorkspaceFactory.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/FSPathHelper.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/BazelQueryProjectStructureStrategy.java
tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerFTest.java

Implement test coverage for the non-maven project structure feature

project structure tests

---

releng/target-platform/target-platform.target
releng/target-platform/target-platform.tpd

2021-06 has been removed from download page.

Update to Eclipse 2021-09

---

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelOutputParser.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelProblem.java
tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/command/BazelOutputParserTest.java

Fixes for the BUILD Problem support in BEF 1.5 on Windows.

BEF 1.5 windows testing fixes

---

bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java
bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelTestClasspathProvider.java

Not huge, but small perf improvement on the first launch of tests for a project. Additional perf improvement seen on second invocation of same tests.

modest perf improv for launching tests

---

tests/com.salesforce.b2eclipse.tests/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporterTest.java

Fix will come when #398 is picked up.

ignore failing test in BJLS

---

bundles/com.salesforce.bazel-java-sdk/aspect/intellij_info_impl.bzl
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/SplitSourcePath.java
bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/logging/EclipseLoggerFacade.java
releng/target-platform/target-platform-dev.target
releng/target-platform/target-platform.tpd

Couple changes needed to discover what was going on. First exception stack traces are not logged in Eclipse. Once logged I noticed a scenario with my test project, which was not handled in BEF. Once that was fixed I could see the issue with aspects causing build issues.

Fix aspect to work with Bazel 5

---

bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestBazelWorkspaceFactory.java
bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestOptions.java
bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/java/TestJavaPackageFactory.java
tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerFTest.java
tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactoryFTest.java
tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java

Test support for #404 use cases

test support for root package targets

---

.mvn/extensions.xml
features/com.salesforce.b2eclipse.jdt.ls.feature/META-INF/MANIFEST.MF
features/com.salesforce.b2eclipse.jdt.ls.feature/README.md
features/com.salesforce.bazel.eclipse.feature/META-INF/MANIFEST.MF
features/com.salesforce.bazel.eclipse.feature/README.md

I tried going to 3.0.0, but that forces adoption of JDK 17.

upgrade tycho to 2.7.5

---

.gitignore
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/jar/JarIdentiferResolver.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/jar/JarNameAnalyzer.java
docs/bef/using_the_feature_classpath.md
tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/index/jvm/jar/JarNameAnalyzerTest.java

exclude header_foo.jar files from global search index

---

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/classpath/impl/JvmInMemoryClasspath.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/classpath/impl/JvmUnionClasspath.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/classpath/impl/strategy/JvmClasspathAspectStrategy.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/classpath/impl/strategy/JvmClasspathPersistedFileStrategy.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/classpath/impl/strategy/JvmClasspathSourceDerivedStrategy.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/classpath/impl/strategy/JvmClasspathStrategy.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/classpath/impl/strategy/JvmClasspathStrategyRequest.java
bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelBuildFile.java
bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java

Getting in position to implement persisted files for classpath data to improve restart performance.

more refinements for the classpath framework

---

bundles/com.salesforce.bazel.sdk/aspects/import/import-and-build.sh

`brew install gtar` fails, updated the reference to install the correct package

updated brew install cmd to reference gnu-tar instead of gtar

---

.github/workflows/cd.yml

Reverts salesforce/bazel-eclipse#480

Revert "Dependabot: Bump actions/upload-pages-artifact from 2 to 3"

---

docs/common/classpath.md

Fix very minor typo in classpath.md doc

---

docs/common/projectviews.md

Related to ~~#112~~ https://github.com/salesforce/bazel-vscode-java/issues/112

Add links to Supported Standard Features docs of .bazelproject

---

docs/common/classpath.md

Minor: Use #### instead of *bold* for sub-section heading in classpath.md doc

---

bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/model/BazelRuleAttributes.java
bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/model/BazelTargetInfo.java
bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/model/discovery/BaseProvisioningStrategy.java
bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/model/discovery/JavaAspectsClasspathInfo.java
bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/model/discovery/classpath/libs/GeneratedLibrariesDiscovery.java
bundles/com.salesforce.bazel.eclipse.ui/src/com/salesforce/bazel/eclipse/ui/jdt/FindClassResolutionsOperation.java
bundles/com.salesforce.bazel.sdk/src/com/salesforce/bazel/sdk/command/querylight/BazelRuleAttribute.java
bundles/com.salesforce.bazel.sdk/src/com/salesforce/bazel/sdk/command/querylight/Rule.java
tests/com.salesforce.bazel.eclipse.core.tests/META-INF/MANIFEST.MF
tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/core/tests/it/Workspace001Test_BasicModelAssumptions.java

Seeing a 2/3 to 3/4 reduction in total memory used.

Reducing memory footprint by excluding unused rule attributes

---

.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
javaConfig.json

baseline set of configs to develop against this project using vscode. The bulk of the support comes from this extension: https://marketplace.visualstudio.com/items?itemName=yaozheng.vscode-pde

added default configs to support development with vscode
