plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelRuntimeClasspathProvider.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegateFTest.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelLauncherBuilderTest.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/AspectPackageInfo.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelBuildFileHelper.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/TargetKind.java, plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/AspectPackageInfosTest.java, plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/BazelBuildFileHelperTest.java
This PR makes BEF aware that Selenium Java targets are interesting. But BEF doesn't really do anything interesting with Selenium targets beyond that. See the #47 work item for more details on follow up work.
=> partial support for Selenium java tests

plugin-core/src/main/java/com/salesforce/bazel/eclipse/BazelPluginActivator.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerInitializer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/ImplicitDependencyHelper.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelRuntimeClasspathProvider.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/old/WorkspaceWizardPage.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/command/BazelCommandRunnerFTest.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockEclipse.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockOperatingEnvironmentDetectionStrategy.java, plugin-libs/plugin-command/BUILD, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelCommandManager.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/TestBazelCommandEnvironmentFactory.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelWorkspace.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelWorkspaceMetadataStrategy.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/OperatingEnvironmentDetectionStrategy.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/RealOperatingEnvironmentDetectionStrategy.java
In working on a fix for the implicit dependencies issue #43 I found I wanted a proper model construct for BazelWorkspace. Prior to this PR, we had workspace concepts scattered around.
Lots of files in this PR to redirect consuming code, but overall a pretty simple model object.
=> refactor to add BazelWorkspace model object

plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/ImplicitDependencyHelper.java
Fixes issue #43 by injecting implicit deps into Eclipse projects that have java_test rules in them.
It is a hacky solution, but we can improve it over time as our query/aspect engine becomes more sophisticated.
=> inject implicit deps into java classpath

plugin-core/src/main/java/com/salesforce/bazel/eclipse/BazelPluginActivator.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/ImplicitDependencyHelper.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/old/WorkspaceWizardPage.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/command/BazelCommandRunnerFTest.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/TestBazelCommandEnvironmentFactory.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelWorkspace.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelWorkspaceCommandOptions.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelWorkspaceMetadataStrategy.java
One last feature for the implicit deps. If build option --explicit_java_test_deps=true is set, we do not add the implicit test deps.
=> added command options model for looking up bazelrc flags

plugin-core/src/main/java/com/salesforce/bazel/eclipse/BazelPluginActivator.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/ImplicitDependencyHelper.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerFTest.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/command/BazelCommandRunnerFTest.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactoryFTest.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegateFTest.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockEclipse.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelLauncherBuilderTest.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunnerTest.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/internal/BazelCommandExecutorTest.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelperTest.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommandBuilder.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/TestBazelCommandEnvironmentFactory.java, plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestAspectFileCreator.java, plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelWorkspaceFactory.java, plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestJavaRuleCreator.java
Finishing adding test support for the Issue #43 implicit test dependency feature. Adding in command option (--explicit_java_test_deps=true) support to the test framework uncovered a few existing bugs in the test framework.
=> test support for implicit/explicit java test deps

feature/feature.xml, plugin-core/META-INF/MANIFEST.MF, plugin-libs/plugin-abstractions/META-INF/MANIFEST.MF, plugin-libs/plugin-command/META-INF/MANIFEST.MF, plugin-libs/plugin-deps/META-INF/MANIFEST.MF, plugin-libs/plugin-model/META-INF/MANIFEST.MF, tools/feature_version_def.bzl
Fixes #54 
We had let several open source package versions float in a few places, including org.json (the reported issue) as well as some google packages. This PR pins those versions to the versions provided by our deps plugin.
=> pin org.json imported version, set BEF version to 1.0.3 for release

plugin-core/resources/bzleclipse_aspect.bzl, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelper.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/AspectPackageInfo.java
This PR enables BEF to detect and add the output jars from **java_proto_library** and **java_grpc_library** rules to the classpath of consuming Eclipse projects. In other words, with this support Eclipse JDT will no longer put red squigglies on proto/grpc-java generated classes at point of usage in Java files.
=> classpath support for protobuf-java and grpc-java

plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelBuildFileHelper.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/TargetKind.java
Adds recognition that BUILD files with proto/grpc-java rules are interesting, and allows the user to import such packages as Eclipse projects. In some cases will display the .proto files in Project Expolorer.
Since convention (at least internally at SFDC) is to splat the .proto file in the same dir as the the BUILD file, the BEF technically hasn't supported that (only src/main/java for source). I made a minimal effort to enable that in this PR, but only partially addressed it. I defer to Issue #8 when we can fully support source files in flexible locations (inc .proto).
Also, this ticket does not add a Project Reference from the consuming project to the project that generates the proto_java_library. I will add a low priority follow up ticket for actually using Eclipse/BEF for iterating on …
=> basic support for importing packages with proto rules

plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizard.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelLabel.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelPackageInfo.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelPackageLocation.java
This is to allow different import code paths - the one based on projectview
file changes won't construct BazelPackageInfo instances.
=> Replace BazelPackageInfo usage with new Interface during import

plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelJavaSourceLookupDirector.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegate.java
@plaird this fixes source lookup if you breakpoint in a diff java project from the one that you are actually debugging (==launching). We still need to fix source lookup for jars (if you breakpoint in code coming from a Nexus jar) - what did you have to get that to work for regular "open type in jar" functionality?
=> Partial fix for debug source lookup - still broken for srcs in jars

plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizard.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizardPage.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelLabel.java
This solves the main feature for #25 
The remaining issue is that the existing projects need to recompute their classpath, as the additive projects may now be a project reference to a classpath.
=> allow additive import of more Bazel packages to existing Eclipse workspace

plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectSupport.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelProjectPreferences.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/EclipseProjectBazelTargets.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationSupport.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelRuntimeClasspathProvider.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/ProjectViewEditor.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizardPage.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactoryFTest.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelper.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelBuildFile.java
I have had a branch set aside where I did the classpath changes to recognize test jars as such in JDT (so they aren't visible to main classes). These refactorings were helpful in implementing that the first time. I am carrying forward these changes before I actually implement the test classpath.
Introduced some new classes to model:
- Eclipse preferences container
- Set of Bazel targets
- Build file
and a lot of code changes to reroute callers into the model objects. And use Set instead of List in places where dupes are not wanted.
=> prep work for splitting test classpath

plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/ImplicitDependencyHelper.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/api/JavaCoreHelper.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/impl/EclipseJavaCoreHelper.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockJavaCoreHelper.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelQueryHelper.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelper.java
First layer of infra code to support identifying test libs as such, so they are added only to the JDT test classpath.
- exposed a boolean isTestLib on the library classpath method
- support for querying a target for its type (i.e. java_test, java_library, java_binary) which is necessary to classify the outputs of the target
=> first phase of testlib support

plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationSupport.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelper.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunnerTest.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelperTest.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/AspectPackageInfos.java
Tracks the target type (java_library, java_test) as it adds jars to the classpath of the JDT project so that test jars are added only to the JDT test classpath, not the main classpath.
=> isolate test deps to the test classpath in JDT

plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelMarkerManagerSingleton.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectSupport.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/ProjectViewEditor.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/builder/BazelBuilderTest.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelMarkerDetails.java, plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/BazelMarkerDetailsTest.java
Also refactor and fix label to error matching.
I think this is good enough for now for #96.
=> Don't drop bazel errors for unimported projects

plugin-core/src/test/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegateFTest.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelLauncherBuilderTest.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommandBuilder.java
the test framework had a bug, such that when we switched to using the launcher script for bazel run, the tests didn't break as expected. fixed the bug, and updated the tests
=> fix launcher tests

plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelErrorStreamObserver.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelMarkerSupport.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelProjectPreferences.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/ProjectViewEditor.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/builder/BazelBuilderTest.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/builder/BazelErrorStreamObserverTest.java, plugin-libs/plugin-abstractions/src/main/java/com/salesforce/bazel/eclipse/abstractions/OutputStreamObserver.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/CommandBuilder.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelCommandExecutor.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/shell/SelectOutputStream.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/shell/ShellCommand.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/shell/ShellCommandBuilder.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/internal/BazelCommandExecutorTest.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelOutputParser.java, plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/BazelOutputParserTest.java
- Create OutputStreamObserver interface for observers of output stream
- Create BazelErrorStreamObserver that implements OutputStreamObserver, which collects build errors as soon as they occur and publish them to Problems View
- Change BazelOutputParser to implement a state so that it can parse errors line by line
- Update unit tests
=> Stream build results as they occur into the Eclipse Problems view

plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelErrorStreamObserver.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelMarkerSupport.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/ProjectViewEditor.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/builder/BazelErrorStreamObserverTest.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/shell/SelectOutputStream.java
This is not working correctly yet, because, although the problem markers are
now created right away, as we parse Bazel output, the problems view doesn't
visually show the markers until after BazelBuilder has completed.
I will create a follow up issue.
=> Some cleanup for issue #41

plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelErrorStreamObserver.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelMarkerSupport.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/ProjectViewEditor.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/builder/BazelErrorStreamObserverTest.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java, plugin-libs/plugin-model/BUILD, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelOutputParser.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelProblem.java, plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/BazelOutputParserTest.java, plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/BazelProblemTest.java
I want to re-use BazelBuildError for publishing JDT warnings to the problems view (yes, I am still looking into that!), so I renamed it to BazelProblem.
=> Rename BazelBuildError -> BazelProblem

plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java
now that projects are imported in the correct order (reverse dep order) we can use cached classpath data during import, for performance
=> use cached classpath data during import

plugin-core/src/main/java/com/salesforce/bazel/eclipse/BazelPluginActivator.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerFTest.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockJavaCoreHelper.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockOperatingEnvironmentDetectionStrategy.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/BazelLauncherBuilderTest.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/MockCommand.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockBuildCommand.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockCleanCommand.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockCustomCommand.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockInfoCommand.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockLauncherCommand.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockQueryCommand.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockTestCommand.java, plugin-libs/plugin-command/src/test/java/com/salesforce/bazel/eclipse/command/mock/type/MockVersionCommand.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/OperatingEnvironmentDetectionStrategy.java, plugin-libs/plugin-model/src/test/java/com/salesforce/bazel/eclipse/model/mock/MockOperatingEnvironmentDetectionStrategy.java, plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelPackageDescriptor.java, plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelTargetDescriptor.java, plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelWorkspaceDescriptor.java, plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestBazelWorkspaceFactory.java, plugin-libs/plugin-testdeps/src/main/java/com/salesforce/bazel/eclipse/test/TestJavaRuleCreator.java
- bazel build/test/query mock commands now verify passed package is actually found in the test workspace, which required fixing some tests too
- reworked exception handling in BazelClasspathContainer, we wrap exceptions when running in the IDE to smooth out timing issues and random failures, but now we run in strict mode for tests so critical problems aren't swallowed
- and more
=> improve accuracy of bazel command level testing

plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/builder/BazelBuilderTest.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelCommandExecutor.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelper.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/shell/ShellCommand.java
This resolves an issue I would see sometimes after a BUILD file change or expanding a project node in the project explorer. There is some Eclipse project locking going on, and trying to regenerate the aspect cache can get stuck. So immediately after flushing the targets for a changed BUILD, we regenerate the aspect info before telling Eclipse to refresh the classpath container.
=> reload flushed aspects

plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/api/ResourceHelper.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/impl/EclipseResourceHelper.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockResourceHelper.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/BazelWorkspaceCommandRunner.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelQueryHelper.java, plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/internal/BazelWorkspaceAspectHelper.java, plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/BazelOutputParser.java
1. if a change to a BUILD file results in adding a dep from one Eclipse project to another, the Project references are updated in the BazelClasspathContainer. But sometimes the resource tree is locked (not always though), and that change needs to be deferred.
2. our Build error parsing logic could not handle build errors from BUILD file issues. I put in a quick workaround, will file a bug to do it right
3. I moved our BUILD query cache down a layer to be closer to the code that actually runs the bazel queries.
=> fixes found during testing of BUILD refresh

plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java
I am temporarily disabling cp refresh until we fix the perf issue in #145 
Eclipse is sending us full build commands way too often, causing long delays as we flush the Aspect and Classpath caches and recompute everything for no reason.
=> stop cp refresh until perf issue fixed

bazel-java-sdk/README.md, docs/dev/architecture.md, docs/dev/dev_guide.md, docs/dev/logging.md, plugin-core/README.md
I sent a handful of big refactor commits directly to master outside of PRs, since the diffs would have been unreadable anyway. This is the resulting doc changes from all of that work.
- collapsed model, abstractions and command plugins into a single bazel-java-sdk plugin
If you are developing BEF (ie. not just using it), and have an Eclipse workspace for it, you will need to re-import your workspace since the structure of BEF is now significantly different.
=> doc updates for bazel-java-sdk refactor

bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmClasspath.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/impl/EclipseResourceHelper.java
I saw a classpath deadlock today (not related to the problem marker deadlock). I believe it was caused by updating the project def in the Eclipse workspace inside of a Java synchronized block.
This PR moves the workspace modifying operation outside of the Java synch block. This is not the last word though, I will file an issue to better integrate with Eclipse's WorkManager to avoid these problems.
=> delay updating project def outside of sync block to avoid deadlocks

bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmClasspath.java
Having dupe project references was causing unnecessary churn on the project description object, and thus unnecessary auto builds.
=> dedupe project references

bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmClasspath.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/BaseBazelClasspathContainer.java
IDE closes in less than a second now. Fixes #156 
Also speeds up import by a decent amount, as saveContainers() is being called during that process too.
=> implement early exit from getClasspath for fast IDE close and other use cases

plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelProjectImporter.java
Fixes #51  The problem was caused by exceptions that have no messages. Now use a default message if the exception does not have one.
=> fixes error dialog during import

plugin-core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferenceInitializer.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferenceKeys.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizardLocationControl.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizardPage.java
This is a worrisome solution for #164. I am not totally comfortable with the solution, but the system Open dialog's behavior does not seem to be configurable. If the WORKSPACE file is a softlink, the Open dialog resolves the soft link to the canonical path. So to support this use case we need to detect that we are in a non-root directory of the Bazel workspace. This could get nasty as Bazel supports nested workspaces, but the solution seems to be ok since it makes sure the found WORKSPACE soft link is pointing to the canonical file identified by the user.
I also added a pref to disable this feature, just in case there is trouble with it. A follow on PR will clean up the prefs stuff, it is a little rough.
=> add support for softlinked workspace files

plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/api/ResourceHelper.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/runtime/impl/EclipseResourceHelper.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/MockResourceHelper.java
Fixes Issue #40 . Supports a Bazel workspace with package names that are not unique, like:
- //projects/path1/apple-api/BUILD (java_library target here)
- //projects/path2/apple-api/BUILD (java_library target here)
this would import into Eclipse with Eclipse projects named:
- apple-api
- apple-api2
I also made some small improvements to how we handle incremental imports (import projects into an existing Eclipse workspace).
=> allow two bazel packages to have same name in same bazel workspace

bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelProcessBuilder.java, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/shell/ShellCommand.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegate.java
There are a few things going on in this PR, I should have made them separate but each is fairly small.
- Temporary solution for rules_docker download timeouts (PULLER_TIMEOUT env var), with #190 filed to implement a better solution.
- More logging during command execution, which I used to narrow in on the problem for this case, but also some incremental work towards #191 
- Implemented solution for #185 which disconnects Bazel clean from Eclipse clean. I didn't implement the pref yet.
- Fixed an untracked bug for the Launcher UI for projects that have no launchable targets, found during the course of doing other business.
=> temp solution for PULLER_TIMEOUT, disconnect bazel clean

bzl-java-sdk/BUILD, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelWorkspaceCommandRunner.java, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelQueryHelper.java, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelWorkspaceAspectHelper.java, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmClasspath.java, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelLabel.java, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelLabelUtil.java, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/BazelProjectTargets.java, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/ProjectView.java, bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/util/BazelDirectoryStructureUtil.java, bzl-java-sdk/src/test/java/com/salesforce/bazel/sdk/command/test/type/MockQueryCommand.java, bzl-java-sdk/src/test/java/com/salesforce/bazel/sdk/model/BazelLabelTest.java, bzl-java-sdk/src/test/java/com/salesforce/bazel/sdk/model/BazelLabelUtilTest.java, plugin-core/BUILD, plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/EclipseClasspathUtil.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/classpath/EclipseImplicitClasspathHelper.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/EclipseBazelProjectManager.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/ProjectImporterFactory.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/EclipseProjectStructureInspector.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/ImportFlow.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/InitImportFlow.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/LoadTargetsFlow.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/ProjectViewEditor.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/projectview/ProjectViewProcessor.java, plugin-core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizardPage.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/builder/EclipseClasspathUtilTest.java, plugin-core/src/test/java/com/salesforce/bazel/eclipse/mock/EclipseFunctionalTestEnvironmentFactory.java
Sorry this PR is a bit large.  There are 2 mains changes:
- I wanted to experiment with different wildcard targets ("all" vs "\*").  We had multiple places in code where we assumed "*", I tried to get rid of those assumptions.
- Import was running one bazel query for imported bazel package. This was a source of slowness - we now run a single bazel query for all configured labels early during import, to populate the query cache.
=> Centralize default target definition, eager bazel query #131

bundles/com.salesforce.bazel-java-sdk/META-INF/MANIFEST.MF, bundles/com.salesforce.bazel.eclipse.core/META-INF/MANIFEST.MF, bundles/com.salesforce.bazel.eclipse.deps/META-INF/MANIFEST.MF, docs/dev/dev_guide.md, docs/dev/dev_issues.md, docs/dev/jdk.md, features/com.salesforce.bazel.eclipse.feature/feature.xml
I didn't checkin the metadata updates when I released 1.3.0. Fixing that by incrementing the metadata to 1.4.0 to get ready for next release.
Also doc updates.
=> inc next version of BEF in meta files, doc updates

bundles/com.salesforce.bazel.eclipse.core/META-INF/MANIFEST.MF, features/com.salesforce.bazel.eclipse.feature/feature.xml
After the Tycho transition, BEF worked fine when launched from the Eclipse SDK. But when the updatesite was built, and the feature was installed in a regular Eclipse, the Bazel Aspect was broken. The Bazel Aspect is a file in a Bazel workspace that is embedded in the BEF Core plugin. We need for the BEF Core plugin to be laid out in extracted form, not a jar, after installation.
The feature we were missing from the Tycho build was that unpacking. Eclipse is an odd duck and it takes a few settings to make that happen:
- unpack=true
- tell it to use the 'dir' shape in the manifest
https://stackoverflow.com/questions/922230/how-do-i-force-an-eclipse-plug-in-to-be-unpacked
=> fix core plugin so it is unpacked

bundles/com.salesforce.bazel-java-sdk.testframework/META-INF/MANIFEST.MF, bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/command/test/MockCommand.java, bundles/com.salesforce.bazel-java-sdk/BUILD, bundles/com.salesforce.bazel-java-sdk/META-INF/MANIFEST.MF, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/aspect/AspectTargetInfo.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelWorkspaceCommandRunner.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/Command.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelCommandExecutor.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelQueryHelper.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelWorkspaceAspectHelper.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/shell/SelectOutputStream.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/shell/ShellCommand.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/shell/ShellCommandBuilder.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelBuildFileHelper.java, bundles/com.salesforce.bazel.eclipse.core/BUILD, bundles/com.salesforce.bazel.eclipse.core/META-INF/MANIFEST.MF, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/builder/ResourceDeltaInspector.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/config/EclipseBazelProjectManager.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegate.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/ProjectImporterFactory.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/EclipseProjectCreator.java, bundles/com.salesforce.bazel.eclipse.deps/BUILD, bundles/com.salesforce.bazel.eclipse.deps/META-INF/MANIFEST.MF, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/aspect/AspectTargetInfosTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/command/BazelOutputParserTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/command/ShellCommandTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/model/BazelLabelUtilTest.java, tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerFTest.java
Having guava in BEF wasn't hurting anything, but we don't want it in bazel-java-sdk as that should be as light as possible. We were only using Guava for a few easily replaceable use cases, so just remove it from BEF entirely.
=> remove guava

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/util/BazelConstants.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/util/BazelDirectoryStructureUtil.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateProjectsFlow.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateRootProjectFlow.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/EclipseFileLinker.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/EclipseProjectCreator.java
The easy part of #180. This only links files that exist when each project is imported. We will need a ResourceChangeListener to link new files as they are created.
=> initial impl for resource files in Package/Project Explorer

.github/create-update-site.sh, .github/update-site-index.html, .github/workflows/build-release-deploy.yml, .gitignore
GitHub pages is now a toplevel index.html with the update-site in a subdir.
https://opensource.salesforce.com/bazel-eclipse/
=> update-site fixes

.github/update-site-index.html, README.md, docs/install.md
Marketplace has a really cool **Install** button feature. Adding it to our site and our docs.
It is already live here:
https://opensource.salesforce.com/bazel-eclipse/index.html
=> add instructions to install from marketplace

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/bep/event/BEPBuildMetricsEvent.java
Contribution by @andrewha12 in bazel-java-sdk repo. BEF doesn't use BEP yet, but we keep the SDK in sync across repos.
=> BEP; extend to include Bazel 5 build metrics

bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/command/test/MockCommandSimulatedOutputMatcher.java, bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestAspectFileCreator.java, bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestBazelPackageDescriptor.java, bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestBazelWorkspaceFactory.java, bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestJavaRuleCreator.java, bundles/com.salesforce.bazel-java-sdk/META-INF/MANIFEST.MF, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/bep/BazelBuildEventsPollingFileStream.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/bep/event/BEPNamedSetEvent.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/bep/file/BEPFileParser.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelOutputDirectoryBuilder.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/jar/JavaJarCrawler.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/source/SourceFileCrawler.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/ImplicitClasspathHelper.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelLabel.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelPackageInfo.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelProblem.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/InMemoryBazelPackageLocation.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/BazelPathHelper.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/workspace/BazelPackageFinder.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/aspect/AspectOutputJarsTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/aspect/AspectTargetInfosTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/command/BazelLauncherBuilderTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/command/BazelOutputDirectoryBuilderTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/model/BazelLabelTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/model/BazelProblemTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/model/BazelWorkspaceTest.java
Work towards better modelling in the SDK to use classes to explicitly model paths such that we don't introduce windows bugs by mistake. This PR mostly adds constants so that "/" and "\" patterns are searchable in the code base.
Lots of diffs because I moved BazelPathHelper into a new package.
=> incremental improvement of path support

releng/target-platform/target-platform.target, releng/target-platform/target-platform.tpd
The following Eclipse platform build doesn't exist anymore: https://download.eclipse.org/eclipse/updates/4.20-I-builds/I20210429-1800/
=> Fix target platform

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/workspace/BazelPackageFinder.java
@guw achtung, a test started failing sometimes in import after applying the Java stream change. HashSet is not thread safe, we need to wrap it in a synchronized collection. You might want to backport this fix to bazel-ls-eclipse.
=> fix concurrency bug in new import

bundles/com.salesforce.bazel.eclipse.core/plugin.xml, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelJunitLaunchConfigurationDelegate.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegate.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelTestRunListener.java, docs/using_the_feature_launching.md
Since early times, we didn't know how to properly wire in Bazel into the Eclipse/JDT standard JUnit launcher code path in Eclipse. We had a workaround with a "Bazel JUnit" test launcher. But it didn't work in all cases.
This PR eliminates the custom launcher. It uses an Eclipse/JDT plug point to swap out the _JUnitLaunchConfigurationDelegate_ instead of the entire launcher. The delegate plug point gives us the ability to change the classpath for tests to use the Bazel classpath, which is what we needed.
After this PR is released, users will need to delete their existing launchers.
Fixes #18 and #251
=> Use standard JUnit launcher for Bazel junit tests #18 #251

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmTestClasspathHelper.java, bundles/com.salesforce.bazel.eclipse.core/plugin.xml, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelJunitLaunchConfigurationDelegate.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelTestClasspathProvider.java, tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/launch/BazelRuntimeClasspathProviderTest.java
Major perf improvement for junit test launchers. Eclipse asks to compute the test classpath multiple times during a launch, so a simple cache dramatically improves junit launch time.
Also:
- Added some more guardrails so that missing param files dont cause errors.
- Refactored the test classpath computation into the SDK.
- Refactored the code to make it more clear what it is doing.
=> improve speed of junit test runs, code refactor for readability and reuse

bundles/com.salesforce.bazel.eclipse.core/plugin.xml, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelTargetLaunchShortcut.java
Small improvements:
- we weren't surfacing the errors when failing to launch a Java class
- we unnecessarily limited the file tree to src/main/java when adding the Bazel Target menu item
=> usability improvements for launching java_binary classes

bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectCreator.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectStructure.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectStructureInspector.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateProjectsFlow.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/DetermineTargetsFlow.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/ImportContext.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/SetupClasspathContainersFlow.java
Simple caching strategy such that we compute the locations of source files in each project only once. The cache lasts for the duration of the import.
=> optimize computation of eclipse project structure on import #273

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmSourceFolderResolver.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/JavaSourceFile.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/SourcePath.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/classpath/EclipseClasspathUtil.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectStructureInspector.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/DetermineTargetsFlow.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/LoadAspectsFlow.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/lang/jvm/JavaSourceFileTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/project/SourcePathTest.java
This is the core implementation of support for non-Maven layouts #8 , which is the main feature of the BEF 1.5.0 release. It will first try to find source files using a Maven layout, since that is the fastest. If that fails, it will resort to using Bazel Query to track down the source folders for the project. This is the better approach, but is much slower so we will try to avoid it.
Right now it is hard coded to look for java files, but I have a handful of follow ups to do with this, including make it lang-pluggable. And some functional tests. Etc.
I will also make the structure strategies pluggable, so we can add more over time and ideally create a way for users to define their own if their company uses a non-Maven, but predictable, layout for their projects.
=> core impl of the non-maven layout support

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/FSTree.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectStructureInspector.java
Follow up PR for #8 to compute a good set of directories containing resource files to add as source directories. The list of resource files come back from Bazel Query, but it is up to us to figure out a good set of non-overlapping directories that contain all of them to add as source directories.
=> support resource files in non-maven projects

bundles/com.salesforce.bazel-java-sdk/META-INF/MANIFEST.MF, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/init/JvmRuleInit.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/MavenProjectStructureStrategy.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/BazelQueryProjectStructureStrategy.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/ProjectStructure.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/ProjectStructureStrategy.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectCreator.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectStructureInspector.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/DetermineTargetsFlow.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/ImportContext.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/SetupClasspathContainersFlow.java
First, this behavior should be in the SDK, not in the Eclipse plugin. Second, each language we support may have one or more strategies for quickly identifying the source directories in a package. We have Bazel Query as the backup, but that is slow so each lang should provide quicker approaches. For example, Java has Maven conventions that are sometimes followed even in Bazel packages. This PR makes all this pluggable.
=> make structure strategies pluggable, move down to SDK

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/init/JvmRuleInit.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/JavaSourcePathSplitterStrategy.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/SourcePathSplitterStrategy.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/SplitSourcePath.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/BazelQueryProjectStructureStrategy.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/project/SourcePathTest.java
When a package does not follow a particular layout convention (e.g. Maven style directory structure) we have to run Bazel Query to find all the source files. Then we need to determine the best directories to use as source paths. To do that, we use language specific logic. This PR makes that logic pluggable. More work on #8.
=> make alg for splitting source paths pluggable

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/MavenProjectStructureStrategy.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/ProjectStructureStrategy.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferenceKeys.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/preferences/BazelPreferencePage.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectCreator.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/InitImportFlow.java, tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/mock/MockEclipse.java, tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/mock/MockIPreferenceStore.java
If the Bazel workspace has a project that is close to Maven-like, but has extra source folders, the Maven project structure strategy will guess wrong and miss those extra folders.
This PR has a pref for disabling the optimization feature. It also fixes an edge case bug in import that I found while doing testing.
=> implement a BEF pref to disable the project struct strategies

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/JavaSourcePathSplitterStrategy.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/FSPathHelper.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/SourcePathSplitterStrategy.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/SplitSourcePath.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/project/SourcePathTest.java
While testing all the PRs for #8, found a weird edge case. Bazel tolerates .java file to be in a directory that does not reflect the package hierarchy.
For example, *Foo.java* is in package *com.salesforce.foo*. Bazel is perfectly happy with it living in source/java/Foo.java. This PR updates the structure strategy to allow this, instead of rejecting the source file as before.
This is all done in the SDK layer, so perhaps some tools will be fine with it. Eclipse will flag the source file with an error because it isn't in the package hierarchy. But at least the issue is now visible to the user.
=> allow java source file not to be nested in package hierarchy

bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/command/test/TestBazelCommandEnvironmentFactory.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmTestClasspathHelper.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelWorkspace.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/BazelProject.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/BazelProjectManager.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/ProjectStructure.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/ProjectStructureStrategy.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/BazelPluginActivator.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelTestClasspathProvider.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectCreator.java, tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/launch/BazelRuntimeClasspathProviderTest.java
The test classpath code had a hard-coded path of src/test/java still, removed that. But also found an issue when the output directory has been cleaned and is missing a some metadata files.
=> enhanced test classpath computation to fix several bugs

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/BazelJvmIndexClasspath.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/JvmCodeIndex.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmClasspath.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/DynamicBazelJvmClasspath.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/JvmClasspath.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/MavenProjectStructureStrategy.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/path/FSPathHelper.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/BazelQueryProjectStructureStrategy.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/structure/ProjectStructure.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainer.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelGlobalSearchClasspathContainer.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/ProjectImporterFactory.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/SetupRootClasspathContainerFlow.java
This is a refactor to make space for a dynamic classpath container.
- It is disabled by default in BazelClasspathContainer
- DynamicBazelJvmClasspath is where the code will go eventually
- The index currently is missing the entries from within the bazel build, which is a problem, there is todo at the bottom of JvmCodeIndex.java that needs to be addressed
@guw if you wanted to do the hackathon, the stub is there in BEF now. There are the above caveats, but I think those I can solve soon. You can focus on parsing the java files and extracting the type info (using trellis?). Look for the TODOs in DynamicBazelJvmClasspath.
=> initial refactor for dynamic classpath

bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestBazelPackageDescriptor.java, bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestBazelWorkspaceDescriptor.java, bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestBazelWorkspaceFactory.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelPackageInfo.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/workspace/BazelPackageFinder.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/workspace/BazelWorkspaceScanner.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/model/BazelPackageInfoTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/workspace/BazelWorkspaceScannerTest.java, tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerFTest.java
This PR changes the behavior at import. We don't currently support the import of nested Bazel workspaces, but the current behavior is to block the import of any Bazel workspace that has one. This PR changes it so the nested workspace is ignored, and the outer Bazel workspace is allowed to be imported.
=> ignore nested workspaces instead of rejecting the import

.github/workflows/link-checker.yml, bundles/com.salesforce.bazel-java-sdk/aspect/README.md, bundles/com.salesforce.bazel.eclipse.core/README.md, bundles/com.salesforce.bazel.eclipse.deps/README.md, docs/README.md, docs/dev/architecture.md, docs/dev/bazeljavasdk.md, docs/dev/dev_guide.md, docs/dev/logging.md, docs/dev/release.md, docs/history.md, docs/install.md, docs/releases.md, features/com.salesforce.b2eclipse.jdt.ls.feature/README.md, features/com.salesforce.bazel.eclipse.feature/README.md
With the Language Server move-in, I will need to do a lot of shuffling of docs. This new CI job will guard against broken links as I do that.
Also fixes 15 existing broken doc links in the repo.
=> CI to check for broken links

bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestBazelWorkspaceFactory.java, bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestOptions.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelLauncherBuilder.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelOutputDirectoryBuilder.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/DetermineTargetsFlow.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/command/BazelLauncherBuilderTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/command/BazelOutputDirectoryBuilderTest.java, tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationDelegateFTest.java
I was improving our test coverage for our Eclipse launchers. I saw that our launchers were using the bazel-bin convenience soft-link, instead of using the actual bazel-bin absolute path. Since everything else uses the absolute paths to bazel-out dirs, I switched the launchers to use absolute path now.
=> launchers refer to absolute path to target

bundles/com.salesforce.bazel-java-sdk.testframework/src/com/salesforce/bazel/sdk/workspace/test/TestBazelWorkspaceFactory.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelOutputParser.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/internal/BazelWorkspaceAspectProcessor.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmTestClasspathHelper.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelJunitLaunchConfigurationDelegate.java
If a java test class is not covered by a java_test rule, we should put up a nice error message instead of class not found.
=> error msg when no java_test rule

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/ArgumentSplitter.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelOutputParser.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/command/BazelWorkspaceCommandRunner.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelProblem.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelErrorPublisher.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/command/BazelOutputParserTest.java, tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/builder/BazelErrorPublisherTest.java
This PR allows BUILD file errors to surface in the Problems view #141. We were also swallowing unhandled build errors, they will now blow back into the UI.
I was working on this for a few days, there was some refactoring and more complexity about resolving paths than expected.
=> rewire error parsing and expose BUILD file errors as Problems

bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/runtime/impl/EclipseResourceHelper.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateRootProjectFlow.java, releng/target-platform/target-platform-dev.target, releng/target-platform/target-platform-dev.tpd, releng/target-platform/target-platform.tpd
Description cannot be used when project is closed. Thus, just the project name should be used.
=> Fix import error when project is closed

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/BazelJvmTestClasspathHelper.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/logging/BasicLoggerFacade.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerInitializer.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelTestClasspathProvider.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/lang/jvm/BazelJvmTestClasspathHelperTest.java
Found the major culprit for #381 
When Bazel builds a java_test target, it can in some cases produce two jars, the normal test jar (with just the compiled test classes) and sometimes a _deploy.jar which is a self contained runnable test executable. The deploy jar has all the deps built in.
For our internal test case, the tests each have 300+ dependencies, so the deploy jars were huge. When launching the tests from Eclipse, Eclipse spawns a new JVM and passes in the proper classpath via the -classpath arg. Also, the Eclipse test launcher is bundled inside. There is no need for the huge bloated deploy jars. So the fix in this PR is to **prevent the deploy jars from being added to the test classpath**.
Also, when running a whole suite of tests at the same time, we created a union classpath …
=> test perf, eliminate deploy jars from test classpath

bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerInitializer.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/component/ComponentContext.java, bundles/com.salesforce.bazel.eclipse.core/plugin.xml, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelCoreClasspathContainerInitializer.java
Fix an issue in BEF caused by the recent refactor of common Bazel Eclipse classes into the Common plugin. We need to make sure the BEF Core plugin is activated before any code in the Core/Common plugins are used. This is because the Core plugin activation establishes all of the collaborators that are used throughout the code base.
The use case where this was failing was:
1. create a new Eclipse workspace 
2. import a Bazel workspace 
3. close Eclipse 
4. launch Eclipse and open the existing Eclipse workspace
This wasn't a problem with the Import Bazel Workspace flow (i.e. new Eclipse workspace use case) because the act of opening the Bazel Import wizard activates the BEF Core plugin.
@AlexeiShmidman I don't know if you need to also have a similar solution for this on the BJLS side, just …
=> fix a bug in BEF activation caused by common plugin refactor

bundles/com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/bazel/eclipse/project/BjlsEclipseProjectCreator.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelLabel.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/model/BazelPackageInfo.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/project/ProjectViewPackageLocation.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/BazelNature.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/classpath/BazelClasspathContainerInitializer.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectCreator.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateProjectsFlow.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateRootProjectFlow.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/runtime/impl/EclipseJavaCoreHelper.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelLaunchConfigurationTab.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/wizard/BazelImportWizard.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/model/BazelLabelTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/model/BazelProjectInfoTest.java
This is the initial support for import of Java targets in the root package (//:*). This is the solution for #404.
This PR does not contain a few things:
- tests
- the ability to NOT import the root package targets; right now they will always be imported
This feature is time sensitive so I will work those items in a follow up PR.
=> initial support for root package BUILD targets

bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/CreateRootProjectFlow.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/ImportContext.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/SetupClasspathContainersFlow.java
Refinement of feature #404 
This allows the user to intentionally unselect the targets in the root package. The previous commit made it so the root targets would always be imported.
Still need unit tests and Windows testing before closing out #404.
=> avoid importing root targets unless explicitly requested

bundles/com.salesforce.b2eclipse.jdt.ls/.settings/JDT.LS Bazel.launch, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/JvmCodeIndex.java, bundles/com.salesforce.bazel.eclipse.common/src/main/java/com/salesforce/bazel/eclipse/project/EclipseProjectCreator.java, bundles/com.salesforce.bazel.eclipse.core/META-INF/MANIFEST.MF, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelJavaSourceLookupDirector.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/launch/BazelTargetLaunchShortcut.java, docs/dev/dev_guide.md, features/com.salesforce.bazel.eclipse.feature/feature.xml
Found that these old deps broke newer Eclipse. Also cleanup up imports.
=> remove dep on logback

bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/CodeIndex.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/CodeIndexReporter.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/CodeIndexer.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/CodeIndexerOptions.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/BazelJvmIndexClasspath.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/JvmCodeIndex.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/JvmCodeIndexer.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/JvmCodeIndexerOptions.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/jvm/jar/JavaJarCrawler.java, bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/index/model/CodeLocationDescriptor.java, bundles/com.salesforce.bazel.eclipse.core/src/main/java/com/salesforce/bazel/eclipse/projectimport/flow/SetupRootClasspathContainerFlow.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/index/jvm/jar/JavaJarCrawlerTest.java, tests/com.salesforce.bazel-java-sdk.tests/src/com/salesforce/bazel/sdk/index/model/CodeLocationDescriptorModelTest.java
Adds the ability to optionally compute an age for each jar in the Global Search index. This isn't surfaced in BEF yet, but can be output in a report (not enabled by default).
While adding optional age computation to the global index, found that the simplistic implementation would benefit from a more robust redesign. Now there is an IndexOptions object to capture runtime options for indexing, there is a CodeIndexer type, and more improvements.
=> major refactor of indexing subsystem

.github/workflows/cd.yml
Reverts salesforce/bazel-eclipse#481
See https://github.com/actions/deploy-pages/issues/286
=> Revert "Dependabot: Bump actions/deploy-pages from 3 to 4"

bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/util/trace/Trace.java, bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/util/trace/TraceTree.java, tests/com.salesforce.bazel.eclipse.core.tests/src/com/salesforce/bazel/eclipse/core/util/trace/TraceGraphDumperTest.java
Adding StartTime into Span so we can add proper hierarchical spans in to telemetry.
This allows to represent the actual hierarchy of calls, because some of them are running in parallel.
=> Adding StartTime into Span so we can add proper hierarchical spans in to telemetry
